# Setup
title:          MuscleViz 
tagline:        fast and easy visualizations for muscle strength testing  
baseurl:        ""
paginate:       1
locale:         "en"

# About/contact
#author:
#  name:       Author name
#  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
